### ISSUE TITLE
Error during adding tiptap package registry to yarn

### ISSUE THREAD

**Issue by KhanShaheb34** [ueberdosis/tiptap-docs#44]
In an attempt to follow to the instructions outlined in [this page](https://tiptap.dev/docs/guides/pro-extensions) for a project using `yarn:4.1.1`, I encountered an issue where yarn persisted in attempting to install the package from `https://registry.yarnpkg.com` instead of `https://registry.tiptap.dev`.

Upon further investigation, I discovered that the suggested solution lies within the `.yarnrc.yml` file. Specifically, the proposed modification involves adding the following configuration:
```
npmScopes:
    "@tiptap-pro":
        npmAlwaysAuth: true
        npmRegistryServer: https://registry.tiptap.dev/
        npmAuthToken: ${TIPTAP_PRO_TOKEN}
```

However, it was observed that removing the `@` from the scope name resolved the issue. Consequently, the modified configuration would be:
```
npmScopes:
    "tiptap-pro":
        npmAlwaysAuth: true
        npmRegistryServer: https://registry.tiptap.dev/
        npmAuthToken: ${TIPTAP_PRO_TOKEN}
```

While I intended to submit a PR to address this issue, I have identified additional areas that require attention. Therefore, I have decided to raise this issue.
